### ISSUE TITLE
Windows Installation procedure fix - Requirements missing?

### ISSUE THREAD

**Issue by LivingSparks10** [byte-pro-max/juxtapose#8]
### Search before asking

- [X] I have searched the JUXTAPOSE [issues](https://github.com/ziqinyeow/juxtapose/issues) and found no similar bug report.

### JUXTAPOSE Component

Other

### Bug

I've tried a clean install on windows following:
`git clone https://github.com/ziqinyeow/juxtapose
cd juxtapose
pip3 install torch --index-url https://download.pytorch.org/whl/cu118
pip install mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html
pip install -r requirements.txt`

and then trying:

`python demo.py`

but it seam that:

`ModuleNotFoundError: No module named 'supervision'`

and I found that requirements.txt it's all commented , I try installing decommenting but:

```
Using cached onnxruntime_gpu-1.16.3-cp310-cp310-win_amd64.whl.metadata (4.5 kB)
ERROR: Could not find a version that satisfies the requirement tapnet (from versions: none)
ERROR: No matching distribution found for tapnet

```

### Environment

Os Windows
Python: 3.10.6
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by byte-pro-max** [comment]
Hey @LivingSparks10, you can remove the `tapnet`, see the dependencies at pyproject.toml file.

Also, I have resolved a ton of dependency issues: #9. 

Run `pip install juxtapose` to install
